### ISSUE TITLE
    - `razorpay_plugin` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

### ISSUE THREAD

**Issue by sohelyadav** [dynamitechetan/razorpay_flutter#19]
Hi, I got this issue while integrating razorpay plugin. 
Xcode version : 10.2.1
swift version: 5
Thank you

`Launching lib/main.dart on iPhone Xʀ in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A razorpay_plugin
      - Flutter
      - firebase_auth
      - firebase_core
      - flutter_facebook_login
      - geocoder
      - geolocator
      - google_api_availability
      - google_maps_flutter
      - google_sign_in
      - location
      - path_provider
      - permission_handler
      - share
      - shared_preferences
      - sqflite

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `flutter_facebook_login` from `.symlinks/plugins/flutter_facebook_login/ios`
    -> Fetching podspec for `geocoder` from `.symlinks/plugins/geocoder/ios`
    -> Fetching podspec for `geolocator` from `.symlinks/plugins/geolocator/ios`
    -> Fetching podspec for `google_api_availability` from `.symlinks/plugins/google_api_availability/ios`
    -> Fetching podspec for `google_maps_flutter` from `.symlinks/plugins/google_maps_flutter/ios`
    -> Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
    -> Fetching podspec for `location` from `.symlinks/plugins/location/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `razorpay_plugin` from `.symlinks/plugins/razorpay_plugin/ios`
    -> Fetching podspec for `share` from `.symlinks/plugins/share/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`

    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      A Bolts
      A FBSDKCoreKit
      A FBSDKLoginKit
      A FBSDKShareKit
      A FMDB
      A Firebase
      A FirebaseAnalytics
      A FirebaseAuth
      A FirebaseAuthInterop
      A FirebaseCore
      A FirebaseInstanceID
      A Flutter
      A GTMSessionFetcher
      A GoogleAppMeasurement
      A GoogleMaps
      A GoogleSignIn
      A GoogleToolboxForMac
      A GoogleUtilities
      A firebase_auth
      A firebase_core
      A flutter_facebook_login
      A geocoder
      A geolocator
      A google_api_availability
      A google_maps_flutter
      A google_sign_in
      A location
      A nanopb
      A path_provider
      A permission_handler
      A razorpay-pod
      A razorpay_plugin
      A share
      A shared_preferences
      A sqflite

    Downloading dependencies

    -> Installing Bolts (1.9.0)
      > Copying Bolts from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/Bolts/1.9.0-ac656` to `Pods/Bolts`

    -> Installing FBSDKCoreKit (4.39.1)
      > Copying FBSDKCoreKit from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/FBSDKCoreKit/4.39.1-f442a` to `Pods/FBSDKCoreKit`

    -> Installing FBSDKLoginKit (4.39.1)
      > Copying FBSDKLoginKit from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/FBSDKLoginKit/4.39.1-c3079` to `Pods/FBSDKLoginKit`

    -> Installing FBSDKShareKit (4.39.1)
      > Copying FBSDKShareKit from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/FBSDKShareKit/4.39.1-27d7b` to `Pods/FBSDKShareKit`

    -> Installing FMDB (2.7.5)
      > Copying FMDB from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/FMDB/2.7.5-2ce00` to `Pods/FMDB`

    -> Installing Firebase (6.0.0)
      > Copying Firebase from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/Firebase/6.0.0-fa80b` to `Pods/Firebase`

    -> Installing FirebaseAnalytics (6.0.0)
      > Copying FirebaseAnalytics from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/FirebaseAnalytics/6.0.0-1743c` to `Pods/FirebaseAnalytics`

    -> Installing FirebaseAuth (6.0.0)
      > Copying FirebaseAuth from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/FirebaseAuth/6.0.0-efc72` to `Pods/FirebaseAuth`

    -> Installing FirebaseAuthInterop (1.0.0)
      > Copying FirebaseAuthInterop from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/FirebaseAuthInterop/1.0.0-0ffa5` to `Pods/FirebaseAuthInterop`

    -> Installing FirebaseCore (6.0.0)
      > Copying FirebaseCore from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/FirebaseCore/6.0.0-e38f0` to `Pods/FirebaseCore`

    -> Installing FirebaseInstanceID (4.0.0)
      > Copying FirebaseInstanceID from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/FirebaseInstanceID/4.0.0-0e034` to `Pods/FirebaseInstanceID`

    -> Installing Flutter (1.0.0)

    -> Installing GTMSessionFetcher (1.2.1)
      > Copying GTMSessionFetcher from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/GTMSessionFetcher/1.2.1-32aec` to `Pods/GTMSessionFetcher`

    -> Installing GoogleAppMeasurement (6.0.0)
      > Copying GoogleAppMeasurement from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/GoogleAppMeasurement/6.0.0-7f028` to `Pods/GoogleAppMeasurement`

    -> Installing GoogleMaps (2.7.0)
      > Copying GoogleMaps from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/GoogleMaps/2.7.0-f79af` to `Pods/GoogleMaps`

    -> Installing GoogleSignIn (4.4.0)
      > Copying GoogleSignIn from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/GoogleSignIn/4.4.0-7ff24` to `Pods/GoogleSignIn`

    -> Installing GoogleToolboxForMac (2.2.0)
      > Copying GoogleToolboxForMac from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/GoogleToolboxForMac/2.2.0-ff316` to `Pods/GoogleToolboxForMac`

    -> Installing GoogleUtilities (6.0.0)
      > Copying GoogleUtilities from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/GoogleUtilities/6.0.0-f1faa` to `Pods/GoogleUtilities`

    -> Installing firebase_auth (0.0.1)

    -> Installing firebase_core (0.0.1)

    -> Installing flutter_facebook_login (0.0.1)

    -> Installing geocoder (0.0.1)

    -> Installing geolocator (3.0.1)

    -> Installing google_api_availability (2.0.0)

    -> Installing google_maps_flutter (0.0.1)

    -> Installing google_sign_in (0.0.1)

    -> Installing location (0.0.1)

    -> Installing nanopb (0.3.901)
      > Copying nanopb from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/nanopb/0.3.901-2901f` to `Pods/nanopb`

    -> Installing path_provider (0.0.1)

    -> Installing permission_handler (3.0.1)

    -> Installing razorpay-pod (1.1.2)
      > Copying razorpay-pod from `/Users/qleverlabstech/Library/Caches/CocoaPods/Pods/Release/razorpay-pod/1.1.2-bd7b4` to `Pods/razorpay-pod`

    -> Installing razorpay_plugin (0.0.1)

    -> Installing share (0.5.2)

    -> Installing shared_preferences (0.0.1)

    -> Installing sqflite (0.0.1)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `razorpay_plugin` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer/xcode/target_validator.rb:122:in `verify_swift_pods_swift_version'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer.rb:578:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer.rb:158:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/command/install.rb:51:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error running pod install
Error launching application on iPhone Xʀ.`

**Comment by SlickSlime** [comment]
Got any solutions to this error?

**Comment by sohelyadav** [comment]
Not now :|

**Comment by sohelyadav** [comment]
@SlickSlime Got the solution. 
1. create a new project with the same name in a different folder including swift support
2.backup your `ios` folder
3. replace current `ios` folder with the `ios` folder created from new project that include swift support.

**Steps to create a flutter project with swift support**

`$ mkdir test`
`$ cd test`
`$ flutter create -i swift your_project_name`
`$ cd ..`
`$ mv your_project_name/ios awesome_project/ios_bak`
`$ mv test/your_project_name/ios awesome_project/ios`
`$ rm -rf test`
`$ cd your_project_name`
`$ flutter packages get`

4. Open project in xcode and change development target to 10.0 
5. Add cocapods and edit the ios/Runner/Info.plist to include permission and rebuild your flutter project.

**Comment by abbasidaniyal** [comment]
Any solution to this apart from re building the ios folder?

**Comment by dynamitechetan** [comment]
I think the main issue is setting target version as 10.0

**Comment by abbasidaniyal** [comment]
I have done that. Still it's giving me this error

**Comment by deliciafernandes** [comment]
> @SlickSlime Got the solution.
> 
> 1. create a new project with the same name in a different folder including swift support
>    2.backup your `ios` folder
> 2. replace current `ios` folder with the `ios` folder created from new project that include swift support.
> 
> **Steps to create a flutter project with swift support**
> 
> `$ mkdir test`
> `$ cd test`
> `$ flutter create -i swift your_project_name`
> `$ cd ..`
> `$ mv your_project_name/ios awesome_project/ios_bak`
> `$ mv test/your_project_name/ios awesome_project/ios`
> `$ rm -rf test`
> `$ cd your_project_name`
> `$ flutter packages get`
> 
> 1. Open project in xcode and change development target to 10.0
> 2. Add cocapods and edit the ios/Runner/Info.plist to include permission and rebuild your flutter project.

Add cocapods and edit the ios/Runner/Info.plist to include permission and rebuild your flutter project. ------> What permission??

**Comment by Thananjeyan** [comment]
`razorpay_flutter` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set
the
               `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.



Facing the same issue. Please post the right solution ?

**Comment by vashisth00** [comment]
I still am having this issue 

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "razorpay_flutter":
  In Podfile:
    razorpay_flutter (from `.symlinks/plugins/razorpay_flutter/ios`)

Specs satisfying the `razorpay_flutter (from `.symlinks/plugins/razorpay_flutter/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by Tabarek** [comment]
> I still am having this issue
> 
> Analyzing dependencies
> [!] CocoaPods could not find compatible versions for pod "razorpay_flutter":
> In Podfile:
> razorpay_flutter (from `.symlinks/plugins/razorpay_flutter/ios`)
> 
> Specs satisfying the `razorpay_flutter (from `.symlinks/plugins/razorpay_flutter/ios`)` dependency were found, but they required a higher minimum deployment target.

+1

**Comment by sayannath** [comment]
Write in Podfile
ENV['SWIFT_VERSION'] = '5'


post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

Do this, it will work!!!

**Comment by karansingla-dev** [comment]
i am also getting this [issue](https://github.com/razorpay/razorpay-flutter/issues/227).

**Comment by karansingla-dev** [comment]
@sayannath  it's a critical error and because of this release is stuck. Can you provide me time estimation?
