### ISSUE TITLE
Issue when deploying AppBundle in playstore.

### ISSUE THREAD

**Issue by RajaShanmugamJM** [dynamitechetan/razorpay_flutter#28]
The app works fine on local development environment but when deployed to play store it crashes on opening gateway.

**Flutter Version :** 
Flutter 1.12.13+hotfix.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9f5ff2306b (9 days ago) • 2020-01-26 22:38:26 -0800
Engine • revision a67792536c
Tools • Dart 2.7.0

**Plugin Version :**
razorpay_plugin : 0.3.0

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chennaieguide.mobile/com.razorpay.CheckoutActivity}: java.lang.ClassNotFoundException: Didn't find class "com.razorpay.d__1_" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.chennaieguide.mobile-f98OWS6waZ_LpgO6jAszlg==/base.apk", zip file "/data/app/com.chennaieguide.mobile-f98OWS6waZ_LpgO6jAszlg==/split_config.arm64_v8a.apk", zip file "/data/app/com.chennaieguide.mobile-f98OWS6waZ_LpgO6jAszlg==/split_config.en.apk", zip file "/data/app/com.chennaieguide.mobile-f98OWS6waZ_LpgO6jAszlg==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.chennaieguide.mobile-f98OWS6waZ_LpgO6jAszlg==/lib/arm64, /data/app/com.chennaieguide.mobile-f98OWS6waZ_LpgO6jAszlg==/base.apk!/lib/arm64-v8a, /data/app/com.chennaieguide.mobile-f98OWS6waZ_LpgO6jAszlg==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.chennaieguide.mobile-f98OWS6waZ_LpgO6jAszlg==/split_config.en.apk!/lib/arm64-v8a, /data/app/com.chennaieguide.mobile-f98OWS6waZ_LpgO6jAszlg==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64]]
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3138)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3289)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2012)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:227)
       at android.app.ActivityThread.main(ActivityThread.java:7211)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:903)
```

**Comment by inirav** [comment]
I have the same issue.

**Comment by RajaShanmugamJM** [comment]
@dynamitechetan 

![image](https://user-images.githubusercontent.com/27273337/76528541-fb2b1c80-6496-11ea-86e7-c8b5c1d97ff3.png)

I tried the following. It just worked. But not sure whether it's the write solution !

```
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}

-keepattributes JavascriptInterface
-keepattributes *Annotation*

-dontwarn com.razorpay.**
-keep class com.razorpay.** {*;}

-optimizations !method/inlining/*

-keepclasseswithmembers class * {
  public void onPayment*(...);
}
```
